{
 "title": "Tower Control",
 "tags": [ "towercontrol" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_TOWERCONTROL", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Wave Progression",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT time AS \"time\", wave FROM wave_events WHERE $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "Resource Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT time AS \"time\", cash_pm, coin_pm FROM resource_rates WHERE $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "Spend Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT time AS \"time\", spend_pm FROM spend_rates WHERE $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "Wave Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT time AS \"time\", waves_ph FROM wave_rates WHERE $__timeFilter(time) ORDER BY time"
    }
   ]
  }
 ]
}